### ISSUE TITLE
Trojan Malware Detected by Antivrus.

### ISSUE THREAD

**Issue by Mas-Si-Osare** [itschasa/Discord-Backup#37] opened 2024-06-11 19:13 UTC
![image](https://github.com/itschasa/Discord-Backup/assets/172434895/dd9f6e9e-ba86-46ef-9f8b-94a1d4072b6d)

**Comment by itschasa** [comment] 2024-06-11 19:14
Duplicate of #24

**Closed as completed** 2024-06-11 19:15 UTC
Labels: duplicate
