### ISSUE TITLE
RELEASE CONTAINS TROJAN (1.20.10 100%, others probable)

### ISSUE THREAD

**Issue by GreenTeaG0D** [itschasa/Discord-Backup#40] opened 2024-11-22 20:28 UTC
Downloaded the release zip, scanned with Microsoft Defender before unzipping, got reported as containing a trojan.

DO NOT DOWNLOAD THIS SOFTWARE.

Detected: Trojan:Win32/Malgent!MSR
Status: Active

containerfile: C:\Users\___MYNAME___\Downloads\backup_windows_v1.2.10.zip

**Comment by itschasa** [comment] 2024-11-22 20:41
Duplicate of #24

**Closed as completed by itschasa** 2024-11-22 20:41 UTC
Labels: duplicate
