### ISSUE TITLE
Feature Suggestion: Message Logs

### ISSUE THREAD

**Issue by EasyAntiCheatSoftware** [itschasa/Discord-Backup#15] opened 2023-05-11 19:37 UTC
Make is so your chat logs in dms can be saved to a txt file. I think that most people will find this very useful.

**Comment by itschasa** [comment] 2023-05-19 16:29
Duplicate of #6

**Closed as completed by itschasa** 2023-05-19 16:29 UTC
Labels: duplicate

**Comment by itschasa** [comment] 2023-08-08 22:18
Refer to #6 (reopened the issue)
